### PR TITLE
Speling

### PR DESCRIPTION
**Pull request by md2perpe**

### CODE REVIEW

**Comment by fabianfiorotto** [comment]
Can you see this README in the package list? I get this error
ERROR: No README data found!

**Comment by md2perpe** [comment]
Here it is: https://github.com/fabianfiorotto/quick-query/blob/master/README.md
What package list? Where do you look for the file?

**Comment by fabianfiorotto** [comment]
I mean in atom. When you click the package in the package list.

**Comment by md2perpe** [comment]
Ah... Yes, I see it.

**Pull request merged**
